version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kairos-api:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: $${{secrets.SPRING_DATASOURCE_URL}}
      SPRING_DATASOURCE_USERNAME: $${{secrets.SPRING_DATASOURCE_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: $${{secrets.SPRING_DATASOURCE_PASSWORD}}
#      JWT_SECRET: 'YourJWTSecretKeyHere'
#      JWT_EXPIRATION_MS: 3600000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - biblio-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $${{secrets.MYSQL_ROOT_PASSWORD}}
      MYSQL_DATABASE: $${{secrets.MYSQL_DATABASE}}
      MYSQL_USER: $${{secrets.MYSQL_USER}}
      MYSQL_PASSWORD: $${{secrets.MYSQL_PASSWORD}}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  biblio-mysql-data:
